### ISSUE TITLE
dependencies install does not work

### ISSUE THREAD

**Issue by Dawsatek22** [barulicm/PiPCA9685#10]
i got this error  in ubuntu server when i tried to install dependecies with the : xargs -a apt_dependencies.txt sudo apt-get install -y command the error is like this : Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python3-distutils is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source . can you help

**Comment by barulicm** [comment]
Sorry for the long delay here. I'm guessing you're using Ubuntu 24, which does not have the python3-distutils package. distutils was deprecated and no longer ships in ubuntu. For now, that means my project won't work on Ubuntu 24. I'll have to switch it over to using setuptools to work in newer environments. I'll try to get to this soon, but can't promise a timeline at the moment.

**Comment by Dawsatek22** [comment]
Thank you for responding. but when you done that can you reply then?

**Comment by barulicm** [comment]
I've updated the build and install setup for this project and tested that it works both in Ubuntu 24 and the latest Raspberry Pi OS.
This issue should be fixed now.

While updating things, I also renamed the default branch to match my other projects. You might need to run these commands to switch your local clone to the new branch name:
```bash
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
