### ISSUE TITLE
cant compile example cpp code

### ISSUE THREAD

**Issue by girs1982** [barulicm/PiPCA9685#3]
root@raspberrypi:/var/www/html/servos/voprosServlib/examples/cpp# gcc main.cpp
/usr/bin/ld: /tmp/cczyiq5T.o: in function `main':
main.cpp:(.text+0x14): undefined reference to `std::allocator<char>::allocator()'
/usr/bin/ld: main.cpp:(.text+0x28): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/usr/bin/ld: main.cpp:(.text+0x3c): undefined reference to `PCA9685::PCA9685(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
/usr/bin/ld: main.cpp:(.text+0x48): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/usr/bin/ld: main.cpp:(.text+0x54): undefined reference to `std::allocator<char>::~allocator()'
/usr/bin/ld: main.cpp:(.text+0x64): undefined reference to `PCA9685::set_pwm_freq(double)'
/usr/bin/ld: main.cpp:(.text+0x78): undefined reference to `PCA9685::set_pwm(int, unsigned short, unsigned short)'
/usr/bin/ld: main.cpp:(.text+0x94): undefined reference to `PCA9685::set_pwm(int, unsigned short, unsigned short)'
/usr/bin/ld: main.cpp:(.text+0xb0): undefined reference to `PCA9685::set_pwm(int, unsigned short, unsigned short)'
/usr/bin/ld: main.cpp:(.text+0xcc): undefined reference to `PCA9685::set_pwm(int, unsigned short, unsigned short)'
/usr/bin/ld: main.cpp:(.text+0xe4): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/usr/bin/ld: main.cpp:(.text+0xf4): undefined reference to `std::allocator<char>::~allocator()'
/usr/bin/ld: main.cpp:(.text+0xf8): undefined reference to `__cxa_end_cleanup'
/usr/bin/ld: /tmp/cczyiq5T.o:(.ARM.extab+0x0): undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status
root@raspberrypi:/var/www/html/servos/voprosServlib/examples/cpp#

**Comment by barulicm** [comment]
Hi! The C++ example code includes a CMake config file (CMakeLists.txt) for building the example code.

Most CMake projects can be built following a process similar to the instructions laid out in the readme for installation. In this case, to build the C++ example code in this repository, follow these commands:

(Make sure you've followed the install instructions from the README first.)

```
cd examples/cpp
mkdir build && cd build
cmake ..
make
```

These commands do the following:
- create a build directory to hold all of the files that the build process generates
- Use CMake to generate a makefile
- Use that generated makefile to build the program

This process will leave you with an executable called "example-cpp" in the build directory you created. Running this program will cycle the servo connected to channel 0 between 4 set positions.

Let me know if you run into any trouble with this build process or if you have any other questions!

**Comment by girs1982** [comment]
thanks
