### ISSUE TITLE
Neither CPP nor Python works

### ISSUE THREAD

**Issue by TonyLiu836** [barulicm/PiPCA9685#7]
Hi, I followed the installation instructions and installed the library. But I can't run any of the examples. 

When I try to run examples.py, I get the following error.
> File "example.py", line 1, in <module>
 from PiPCA9685.PiPCA9685 import PCA9685
ImportError: No module named PiPCA9685

Then when I try to compile the cpp code, I get the following error after running `cmake ..`

> CMake Error at CMakeLists.txt:6 (find_package):
  By not providing "FindPiPCA9685.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "PiPCA9685", but CMake did not find one.
  Could not find a package configuration file provided by "PiPCA9685" with
  any of the following names:
    PiPCA9685Config.cmake
    pipca9685-config.cmake
  Add the installation prefix of "PiPCA9685" to CMAKE_PREFIX_PATH or set
  "PiPCA9685_DIR" to a directory containing one of the above files.  If
  "PiPCA9685" provides a separate development package or SDK, be sure it has
  been installed.
-- Configuring incomplete, errors occurred!
See also "/home/bdog/PiPCA9685/examples/cpp/build/CMakeFiles/CMakeOutput.log".

The raspberry pi I'm using runs Ubuntu Mate 18.04 beta 1 with python2.7. 
I'm not quite sure what I'm doing wrong during the installation process, any help would be greatly appreciated. 

Thanks!

**Comment by barulicm** [comment]
Did you see any errors during the installation process? In particular, while running these commands from the readme:
```
cmake -B build
cmake --build build
sudo cmake --install build
cmake --build build --target install_python
```

I haven't tested the latest version with Python 2. If you do want to use 2.7, you'll need to set `PYBIND11_PYTHON_VERSION ` when configuring the project. So, the first line from the block above would instead be this:

```
cmake -B build -DPYBIND11_PYTHON_VERSION=2.7
```

**Comment by TonyLiu836** [comment]
After cloning and install dependencies from apt, I tried running this:
```cmake -B build -DPYBIND11_PYTHON_VERSION=2.7```
but it gave me 
```
CMake Error: The source directory "/home/bdog/PiPCA9685/build" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
```
After I made a build directory and tried the command again and got this as the error: 
```
CMake Error: The source directory "/home/bdog/PiPCA9685/build" does not appear to contain CMakeLists.txt.
```
I then ran `cmake -DPYBIND11_PYTHON_VERSION=2.7 ..` in the build directory.

Then I ran the following in the PiPCA9685 directory which all seemed to run fine and produced no errors.
```
cmake -B build
cmake -DPYBIND11_PYTHON_VERSION=2.7 --build build
sudo cmake -DPYBIND11_PYTHON_VERSION=2.7 --install build 
```

Running the final command, `cmake -DPYBIND11_PYTHON_VERSION=2.7 --build build --target install_python` produced the following error:
```
bdog@bdog-desktop:~/PiPCA9685$ cmake -DPYBIND11_PYTHON_VERSION=2.7 --build build --target install_python
CMake Error: The source directory "/home/bdog/PiPCA9685/install_python" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
```

Sorry I'm quite new to using CMake, thanks for understanding.

**Comment by barulicm** [comment]
Ah the readme instructions were written using some newer features of CMake (in particular the `-B` flag).

This set of commands should work with CMake 3.10 (which I believe is the version Ubuntu 18 uses)

```
mkdir build
cd build
cmake -DPYBIND11_PYTHON_VERSION=2.7 build ..
cmake --build .
sudo cmake --install .
cmake --build . --target install_python
```

**Comment by Dawsatek22** [comment]
i got this error when i tried to install dependecies with the : xargs -a apt_dependencies.txt sudo apt-get install -y command the error islike this :  Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python3-distutils is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-distutils' has no installation candidate

can you help?

**Comment by barulicm** [comment]
Hi @Dawsatek22, please consider opening a new issue [here](https://github.com/barulicm/PiPCA9685/issues/new/choose) as it does not appear your problem is related to the discussion above. When you do, let me know what operating system (distro and version) you are trying to use. That will let me help you figure out how to get the dependencies set up.
